/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "mslmhopfltsfxsgqqvkc"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1zbG1ob3BmbHRzZnhzZ3FxdmtjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAyMjk5NTEsImV4cCI6MjA4NTgwNTk1MX0.-oSKtR4V-oxnbO_en9oPzRlKjttbt0n8vdbNx5c4mHM"